language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
after_script:
  - npm install -g codeclimate-test-reporter
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info